mypoll/urls.py
from django.urls import path
from mypoll import views

app_name = "mypoll"
urlpatterns = [
    path("", views.home_page, name="homepage"),
    path("vote/<int:question_id>/" , views.vote , name="vote"),
    path('results/<int:question_id>/', views.results, name='results'),
    path("private/", views.private_poll, name="private_poll"),
    path("private/<int:question_id>/", views.onlypoll, name="onlypoll")
]

quizw12/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = "mypoll"
urlpatterns = [
    path('', include('mypoll.urls', namespace='mypoll')),
    path('admin/', admin.site.urls),
]

mypoll/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    is_private = models.BooleanField(default=False)
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mypoll/views.py
from django.shortcuts import get_object_or_404, render, redirect
from mypoll.models import Question , Choice
from django.utils import timezone

def home_page(request): 
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now(),is_private=False).order_by("-pub_date")[:5]

    question_rating = []

    for question in latest_question_list:
        total_votes = 0
        choices = question.choice_set.all()
        for choice in choices:
            total_votes += choice.votes

        if total_votes >= 50:
            rating = "!!Hot"
        elif total_votes >= 10:
            rating = "!Warm"
        else:
            rating = ""
                
        question.rating = rating
        question_rating.append(question)

    return render(request, "home.html" , {'latest_question_list':question_rating})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'home.html', {
            'latest_question_list': [question],
            'error_message': "คุณยังไม่ได้เลือกตัวเลือกใดๆ",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('mypoll:results', question_id=question.id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})


def private_poll(request):
    latest_question_list = Question.objects.filter(pub_date__lte=timezone.now(),is_private=True).order_by("-pub_date")[:5]

    question_rating = []

    for question in latest_question_list:
        total_votes = 0
        choices = question.choice_set.all()
        for choice in choices:
            total_votes += choice.votes

        if total_votes >= 50:
            rating = "!!Hot"
        elif total_votes >= 10:
            rating = "!Warm"
        else:
            rating = ""
                
        question.rating = rating
        question_rating.append(question)

    return render(request, "private_poll.html" , {'latest_question_list':question_rating})


def onlypoll(request,question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    if question.is_private == False:
        return redirect('/')
    return render(request, 'onlypoll.html', {'question': question})

mypoll/templates/home.html
<html>
  <head>
    <title>mypoll</title>
  </head>
  <body>
    <h1>My Poll</h1>
    {% if latest_question_list %}
      <ul>
        {% for question in latest_question_list %}
          <li>
            <h2 id="question{{question.id}}">{{ question.question_text }} - {{question.rating}}</h2>
            <form action="{% url 'mypoll:vote' question.id %}" method="post">
              {% csrf_token %}
              <fieldset>
                {% if error_message %}
                  <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                {% for choice in question.choice_set.all %}
                  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
              </fieldset>
              <input id ="vote" type="submit" value="Vote">
            </form>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

mypoll/templates/onlypoll.html
<html>
  <head>
    <title>mypoll</title>
  </head>
  <body>
    <h1>Only you poll</h1>
    <h2 id="question{{question.id}}">{{ question.question_text }}</h2>
    <form action="{% url 'mypoll:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input id ="vote" type="submit" value="Vote">
    </form>
  </body>
</html>

mypoll/templates/private_poll.html
<html>
  <head>
    <title>mypoll</title>
  </head>
  <body>
    <h1>Private polls</h1>
    {% if latest_question_list %}
      <ul>
        {% for question in latest_question_list %}
          <li>
            <h2 id="question{{question.id}}">{{ question.question_text }} - {{question.rating}}</h2>
            <form action="{% url 'mypoll:vote' question.id %}" method="post">
              {% csrf_token %}
              <fieldset>
                {% if error_message %}
                  <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                {% for choice in question.choice_set.all %}
                  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
              </fieldset>
              <input id ="vote" type="submit" value="Vote">
            </form>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

mypoll/templates/results.html
<html>
  <head>
    <title>result</title>
  </head>
  <body>
    <h1>results</h1>
    <h2>{{ question.question_text }}</h2>
    <ul>
      {% for choice in question.choice_set.all %}
        <li>
          {{ choice.choice_text }} -- คะแนน: {{ choice.votes }}
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'mypoll:homepage' %}">กลับไปหน้าหลัก</a>
  </body>
</html>